#
version: "3.9"

volumes:
  django_logs: {}

services:
  django:
    build:
      context: ../../
      dockerfile: ./Dockerfile
    image: production_django:0.1.0
    container_name: production_django
    platform: linux/x86_64
    command: /start
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - DJANGO_ADMIN_URL=${DJANGO_ADMIN_URL}

    ports:
      - "80:8000"
